"""added photo to community

Revision ID: ca75901aabcd
Revises: 2351cf45a149
Create Date: 2024-03-27 09:41:49.959543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca75901aabcd'
down_revision = '2351cf45a149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=False))

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
